laszlojakab/homeassistant-easycontrols

- custom_components/easycontrols/strings.json
- custom_components/easycontrols/translations/de.json
- custom_components/easycontrols/translations/en.json
- Fixes some grammatical errors in english translation
- Adds german translation
> Improve localization

- .github/workflows/hassfest.yml
- custom_components/easycontrols/manifest.json
Add hassfest github action from [homeassistant](https://developers.home-assistant.io/blog/2020/04/16/hassfest/) and fix detected issue in `manifest.json`
> Add Hassfest workflow

- custom_components/easycontrols/__init__.py
- custom_components/easycontrols/binary_sensor.py
- custom_components/easycontrols/config_flow.py
- custom_components/easycontrols/const.py
- custom_components/easycontrols/fan.py
- custom_components/easycontrols/sensor.py
- custom_components/easycontrols/threadsafe_controller.py
This PR adds doc strings and type annotations to code. Fixes some linter errors. It also changes strings to use single quotes everywhere. 
Fixes #16
> feat: add doc strings, type annotations

- custom_components/easycontrols/sensor.py
This PR changes unit_of_measurement ot native_unit_of_measurement in SensorEntityDescription instances.
Fixes: #23
> feat: use native_unit_of_measurement

- custom_components/easycontrols/fan.py
This PR changes to use extra_state_attributes instead of device_state_attribute property.
Fixes: #25
> feat: use extra_state_attributes

- custom_components/easycontrols/binary_sensor.py
- custom_components/easycontrols/sensor.py
This PR modifies the code to handle sensor availability correctly.
Fixes: #27
> fix: handle sensor availability correctly

- custom_components/easycontrols/fan.py
- custom_components/easycontrols/manifest.json
- custom_components/easycontrols/sensor.py
This PR creates v0.4.5 release.
> release: v0.4.5

- custom_components/easycontrols/fan.py
This PR fixes the issue that set_variable signature change and fan was not updated according to this.
> fix: use 2 parameter for set_variable

- custom_components/easycontrols/manifest.json
The PR creates release v0.4.6.
> feat: release v0.4.6

- custom_components/easycontrols/const.py
- custom_components/easycontrols/fan.py
- custom_components/easycontrols/services.yaml
This PR creates start_party_mode, and stop_party_mode service. It also creates a warning log message when using old party_mode service.
Fixes #38
> feat: create start_party_mode, stop_party_mode service

- custom_components/easycontrols/const.py
- custom_components/easycontrols/fan.py
This PR removes deprecated speed_list, speed properties and uses percentage property instead.
Fixes: #18
> feat: remove deprecated speed, speed_list

- custom_components/easycontrols/const.py
- custom_components/easycontrols/fan.py
This PR add support for preset modes.
Resolves #41
> feat: add preset modes support

- custom_components/easycontrols/__init__.py
This PR adds configuration url.
Fixes #13
> feat: add configuration_url

- custom_components/easycontrols/binary_sensor.py
- custom_components/easycontrols/sensor.py
This PR adds diagnostic entity_category to sensors and binary_sensors.
> feat: add entity_category

- .github/workflows/validate.yml
- hacs.json
This PR adds hacs validation github workflow (https://github.com/hacs/action).
> feat: add HACS validation github workflow

- .github/workflows/validate.yml
- custom_components/easycontrols/manifest.json
- hacs.json
This PR creates release v0.5.0
> feat: release v0.5.0

- README.md
This PR adds shields to README.md.
> feat: add shields to readme

- README.md
This PR adds bymeacoffee shield to README.md.
> feat: add buymeacoffee shield

- .github/scripts/update_hacs_manifest.py
- .github/workflows/release.yml
- hacs.json
This PR adds zip_release to hacs.json and create release github workflow.
> feat: add zip_release to hacs.json

- .github/workflows/release.yml
This PR fixes the path of folder to zip in release.yml.
> fix: zip correct folder in release.yml

- README.md
This PR adds total downloads shield to README.md.
> feat: add total downloads shield

- custom_components/easycontrols/manifest.json
This PR creates release 0.5.4-beta.
> feat: release 0.5.4-beta

- .github/scripts/update_hacs_manifest.py
- .github/workflows/release.yml
- .github/workflows/validate.yml
- LICENSE
- README.md
- custom_components/easycontrols/__init__.py
- custom_components/easycontrols/binary_sensor.py
- custom_components/easycontrols/const.py
- custom_components/easycontrols/fan.py
- custom_components/easycontrols/manifest.json
- custom_components/easycontrols/sensor.py
- custom_components/easycontrols/services.yaml
- hacs.json
This PR creates release 0.5.4-beta.
> merge: create release 0.5.4-beta

- README.md
This PR adds the integration usage badge to `readme.md`.
> feat: add integration usage to readme.md.

- custom_components/easycontrols/__init__.py
- custom_components/easycontrols/binary_sensor.py
- custom_components/easycontrols/config_flow.py
- custom_components/easycontrols/controller.py
- custom_components/easycontrols/fan.py
- custom_components/easycontrols/modbus_variable.py
- custom_components/easycontrols/sensor.py
This PR modifies the code to use `AsyncEazyController` class from eazyctrl package v0.4.
Fixes #63 
References #15
> feat: use AsyncEazyController

- README.md
- custom_components/easycontrols/manifest.json
This PR creates release v0.5.5.
> feat: create release 0.5.5

- custom_components/easycontrols/manifest.json
This PR creates release v0.5.6-beta.
> feat: create release 0.5.6-beta

- custom_components/easycontrols/manifest.json
This PR creates release 0.5.6-beta2
> build: bump version to 0.5.6-beta2

- custom_components/easycontrols/manifest.json
- custom_components/easycontrols/sensor.py
This PR creates release 0.5.6-beta2.
> feat: create release 0.5.6-beta2

- custom_components/easycontrols/manifest.json
This PR prepares release 0.5.6.
> feat: prepare release 0.5.6

- custom_components/easycontrols/manifest.json
This PR creates release 0.5.6.
> feat: create release 0.5.6

- custom_components/easycontrols/manifest.json
This PR creates release 0.5.6.
> feat: create release 0.5.6 (#76)

- custom_components/easycontrols/manifest.json
This PR prepares release 0.5.7.
> feat: prepare release 0.5.7

- custom_components/easycontrols/__init__.py
- custom_components/easycontrols/manifest.json
> feat: create release 0.5.7

- custom_components/easycontrols/__init__.py
- custom_components/easycontrols/binary_sensor.py
- custom_components/easycontrols/config_flow.py
- custom_components/easycontrols/const.py
- custom_components/easycontrols/controller.py
- custom_components/easycontrols/fan.py
- custom_components/easycontrols/modbus_variable.py
- custom_components/easycontrols/sensor.py
This PR reformats code with `black` and consoldates docstring to google style.
> refactor: reformat code

- .github/workflows/continuous-integration-workflow.yml
- custom_components/__init__.py
- custom_components/easycontrols/controller.py
- custom_components/easycontrols/fan.py
- custom_components/easycontrols/modbus_variable.py
- custom_components/easycontrols/sensor.py
- pylintrc
This PR adds linter to github workflow and also fixes linter errors.
> feat: add linter to workflow

- custom_components/easycontrols/manifest.json
This PR prepares release  `0.6.0-beta`.
> build: bump version to 0.6.0-beta

- custom_components/easycontrols/manifest.json
This PR prepares release  `0.6.0`.
> build: bump version to 0.6.0

- custom_components/easycontrols/manifest.json
This PR creates release `0.6.0`.
> feat: create release 0.6.0

- custom_components/easycontrols/manifest.json
This PR prepares release `0.7.0`.
> feat: prepare release 0.7.0
